# frozen_string_literal: true

ruby '2.5.1'

source 'https://rubygems.org'

gem 'activesupport', '~>5.2.0', require: false
gem 'rack-unreloader'
gem 'rake'
gem 'roda'
gem 'puma'
gem 'mongo'
gem 'settingslogic'
gem 'oj'
gem 'rack-cache'
gem 'brotli'
gem 'rack-brotli'
gem 'parallel'
gem 'ruby-time_range'

group :development do
  gem 'rubocop', require: false
end

group :development, :test do
  gem 'pry'
  gem 'looksee'
  gem 'ffi'
  gem 'colorize'
  gem 'pry-bond'
  gem 'pry-inline'
  gem 'pry-clipboard'
  gem 'awesome_print'
  gem 'pry-byebug'
  gem 'hirb'
  gem 'rspec'
end

group :test do
  gem 'database_cleaner'
  gem 'rack-test'
  gem 'simplecov', require: false
end
