#!/usr/bin/env ruby
# warn_indent: true
# frozen_string_literal: true

ruby '>=2.6.3'

source 'https://rubygems.org'

# gem 'caddy', '~>1.6.0'
gem 'childprocess', '~>1.0.1'
gem 'concurrent-ruby-ext', '~>1.1.5', require: false
gem 'mongo', '~>2.8.0'
gem 'oj', '~>3.7.12'
gem 'parallel', '~>1.17.0'
gem 'puma', '~>3.12.1'
gem 'rack', '~>2.1.4'
gem 'rake', '~>12.3.1'
gem 'roda', '~>3.20.0'
gem 'ruby-time_range', require: 'time_range'
gem 'settingslogic', '~>2.0.9'
gem 'tzinfo', '~>2.0'
gem 'tzinfo-data', '~>1.2018.7'
# gem 'ruby-prof'
# gem 'brotli'
# gem 'rack-brotli'

group :production do
  # gem "rack-cache", "~>1.8.0"
end

group :development, :test do
  gem 'awesome_print', '~>1.8.0'
  gem 'byebug', '~>11.0.1'
  gem 'colorize', '~>0.8.1'
  gem 'ffi', '~>1.11.1'
  gem 'hirb', '~>0.7.3'
  gem 'looksee', '~>4.1.0'
  gem 'pry', '~>0.12.2'
  gem 'pry-bond', '~>0.0.1'
  gem 'pry-byebug', '~>3.7.0'
  gem 'pry-clipboard', '~>0.1.1'
  gem 'pry-state', '~>0.1.10'
  gem 'rspec', '~>3.8.0'
  gem 'rubocop', '~>0.70.0', require: false
  gem 'rubocop-performance', '~>1.3.0', require: false
  gem 'rufo', '~>0.7', require: false
end

group :test do
  gem 'rack-test'
  gem 'simplecov', require: false
end
