# frozen_string_literal: true

ruby '2.5.1'

source 'https://rubygems.org'

gem 'caddy', '~>1.6.0'
gem 'childprocess', '~>0.9.0'
gem 'concurrent-ruby-ext', '~>1.1.4', require: false
gem 'mongo', '~>2.6.2'
gem 'oj', '~>3.7.5'
gem 'puma', '~>3.12.0'
gem 'rake', '~>12.3.1'
gem 'roda', '~>3.15.0'
gem 'ruby-time_range', require: 'time_range'
gem 'settingslogic', '~>2.0.9'
gem 'tzinfo', '~>2.0'
gem 'tzinfo-data', '~>1.2018.7'
# gem 'ruby-prof'
# gem 'brotli'
# gem 'rack-brotli'

group :production do
  # gem "rack-cache", "~>1.8.0"
end

group :development, :test do
  gem 'awesome_print', '~>1.8.0'
  gem 'colorize', '~>0.8.1'
  gem 'ffi', '~>1.9.25'
  gem 'hirb', '~>0.7.3'
  gem 'looksee', '~>4.0.0'
  gem 'pry', '~>0.11.3'
  gem 'pry-bond', '~>0.0.1'
  gem 'pry-byebug', '~>3.6.0'
  gem 'pry-clipboard', '~>0.1.1'
  gem 'pry-inline', '~>1.0.4'
  gem 'rspec', '~>3.8.0'
end

group :test do
  gem 'rack-test'
  gem 'simplecov', require: false
end
